name: publish ErrorOr to nuget
on:
    workflow_dispatch:
    push:
        branches:
            - main # Default release branch
        paths:
            - "src/**"
jobs:
    publish:
        name: build, pack & publish
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 8.0.100

            # Publish
            - name: Package
              run: dotnet pack -c Release src/ErrorOr.csproj
            - name: Publish
              run: dotnet nuget push .\artifacts\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
